Hw6
irmerdonmz/Phyton pull request #5
Opened 2023-05-23 16:09 UTC by irmerdonmz

I added HW6

2023-05-25 12:25 UTC, AnastasiiaGor requested changes

2023-05-25 12:25 UTC, AnastasiiaGor commented on HW6/hw6_ig.py
> +    for elem in elems:
The function should work correctly with any type of iterable oblects:

example input: {'one': 1, 'two': 2}
actual output: {'one': 1, 'two': 2} 
expected: o n e t w o

2023-06-03 11:42 UTC, irmerdonmz commented on HW6/hw6_ig.py
> +    for elem in elems:
I updated my HW6

2023-06-05 13:52 UTC, AnastasiiaGor approved these changes

2023-06-05 13:52 UTC, AnastasiiaGor commented on HW6/hw6_ig.py
> +    for elem in elems:
it would be easier check if element is iterable using hasattr(elem, '__iter__')

2023-06-05 13:56 UTC, closed without merging